name: animated_custom_dropdown
description: Highly customizable animated dropdown widget. Features include search on list data, network search with infinite scroll (pagination), multi-selection, configurable overlay animations, a floating label and more.
version: 4.0.0
homepage: https://github.com/AbdullahChauhan/custom-dropdown
repository: https://github.com/AbdullahChauhan/custom-dropdown
issue_tracker: https://github.com/AbdullahChauhan/custom-dropdown/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

funding:
  - https://buymeacoffee.com/abdullahchauhan

screenshots:
  - description: "Custom dropdown Preview"
    path: screenshots/preview.png
  - description: "Dropdown example"
    path: screenshots/example_1.jpg
  - description: "Search dropdown example"
    path: screenshots/example_2.jpg
  - description: "Multi select dropdown example"
    path: screenshots/example_3.jpg

topics:
  - ui
  - dropdown
  - spinner
  - widget
  - widgets
